version: 2
project_name: lazysshterm

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    ignore:
      # ponytail: go toolchain doesn't support windows/arm
      - goos: windows
        goarch: arm
    main: ./cmd/lazysshterm/main.go
    ldflags:
      -X main.version={{.Version}} -X main.gitCommit={{.Commit}}



archives:
  - formats: [ tar.gz ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
        {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ zip ]

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - repository:
      owner: btafoya
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/btafoya/lazysshterm"
    description: "A simple terminal UI for managing SSH connections.  "
    license: "Apache-2.0"

release:
  footer: >-
    
    ---
    
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
